version: '3.8'
services:
    service_1:
        image: aabdur-rahman/service1
        build: ./service1
        ports:
            - target: 5000
              published: 5000
              protocol: tcp
              depends_on: 
                - service2
                - service3
                - service4
        environment:
            DATABASE_URI: ${DATABASE_URI}
            SECRET_KEY: ${SECRET_KEY}
    service_2:
        image: aabdur-rahman/service2
        build: ./service2
        ports:
            - target: 5001
              published: 5001
              protocol: tcp
    service_3:
        image: aabdur-rahman/service3
        build: ./service3
        ports:
            - target: 5002
              published: 5002
              protocol: tcp
    service_4:
        image: aabdur-rahman/service4
        build: ./service4
        ports:
            - target: 5003
              published: 5003
              protocol: tcp
            